In [32]:
import pandas as pd
#데이터 로드
X_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/MedicalCost/x_train.csv")
Y_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/MedicalCost/y_train.csv")
X_test= pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/MedicalCost/x_test.csv")


# display(X_train.head())
# display(Y_train.head())
# print(X_train.info())

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
X_train.sex = encoder.fit_transform(X_train.sex)
X_test.sex = encoder.transform(X_test.sex)
X_train.smoker = encoder.fit_transform(X_train.smoker)
X_test.smoker = encoder.transform(X_test.smoker)
X_train.region = encoder.fit_transform(X_train.region)
X_test.region = encoder.transform(X_test.region)

# display(X_train)
# print(X_train.info())
# print(X_train.describe())

x_test_id = X_test.ID

from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val = train_test_split(X_train,Y_train,test_size=0.2)
from sklearn.ensemble import RandomForestRegressor
model1 = RandomForestRegressor(n_estimators=1000,max_depth=None)
model1.fit(x_train,y_train.charges)
y_train_predicted = model1.predict(x_train)
y_val_predicted = model1.predict(x_val)

from sklearn.metrics import r2_score
print(r2_score(y_train_predicted,y_train.charges))
print(r2_score(y_val_predicted,y_val.charges))

y_test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/MedicalCost/y_test.csv')

result1 = model1.predict(X_test)
print(r2_score(result1,y_test.charges))
model2 = RandomForestRegressor(n_estimators=1000,max_depth=None)
model2.fit(X_train,Y_train.charges)
result2 = model2.predict(X_test)
print(r2_score(result2,y_test.charges))

final = pd.concat([x_test_id,pd.DataFrame(result2,columns=['charges'])],axis=1)
final.to_csv('12345.csv',index=False)

final = pd.read_csv('12345.csv')
display(final)

0.9767246425294309
0.8287350352202756
0.9093652987518911
0.9161022832538669

       ID       charges
0       0   6794.614577
1       1   2773.853916
2       5   8349.988517
3      21   8388.367490
4      26  12970.295130
..    ...           ...
263  1327  14466.538173
264  1328  16445.541731
265  1329   5521.656161
266  1331  35477.567499
267  1334  13179.897230

[268 rows x 2 columns]