In [44]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/youtube.csv",index_col=0)
# display(df.head())

# print(list(df.loc[df.channelId.isin(df.channelId.value_counts().head(10).index)].channelTitle.unique()))

# print(list(df.loc[(df.dislikes) > (df.likes),'channelTitle'].unique()))

change = df[['channelTitle','channelId']].drop_duplicates().channelId.value_counts()
target = change[change>1]
# print(len(target))

df.trending_date2 = pd.to_datetime(df.trending_date2)
# print(df.loc[df.trending_date2.dt.day_name()=='Sunday'].categoryId.value_counts().index[0])

group = df.groupby([df.trending_date2.dt.day_name(),'categoryId'],as_index=False).size()
# print(group.pivot(index='categoryId',columns='trending_date2'))

target2 = df.loc[df.view_count!=0]
t = target2.copy()
t['ratio'] = (target2.comment_count/target2.view_count).dropna()
# print(t.sort_values(by='ratio',ascending=False).iloc[0].title)

# print(t.loc[t.ratio>0].sort_values(by='ratio',ascending=True).iloc[0].title)

target3 = df.loc[(df.likes!=0)&(df.dislikes!=0)]
t = target3.copy()
t['ratio'] = target3.dislikes/target3.likes
# print(t.sort_values(by='ratio',ascending=True).iloc[0].title)

# print(df.loc[df.channelId==df.channelId.value_counts().index[0]].channelTitle.unique()[0])

# print((df[['title','channelId']].value_counts()>=20).sum())

40

Q11

In [45]:
import pandas as pd


channel =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/channelInfo.csv')
video =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/videoInfo.csv')
# display(channel.head())
# display(video.head())

,channelid,subcnt,viewcnt,videocnt,ct,channelname
0,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,410238653,736,2021-09-30 03:01:03,꽈뚜룹
1,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,736,2021-09-30 09:01:03,꽈뚜룹
2,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,735,2021-09-30 15:01:03,꽈뚜룹
3,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,737,2021-09-30 21:01:03,꽈뚜룹
4,UCkQCwnkQfgSuPTTnw_Y7v7w,1320000,412531322,737,2021-10-01 03:01:04,꽈뚜룹

,videopk,viewcnt,likecnt,dislikecnt,favoritecnt,cmcnt,ct,videoname
0,c5JQp6xafqc,1667010,30474,706,0,6587,2021-10-10 15:20:03,공범 EP1
1,c5JQp6xafqc,1669089,30495,707,0,6589,2021-10-10 15:30:03,공범 EP1
2,c5JQp6xafqc,1674759,30522,711,0,6596,2021-10-10 15:40:02,공범 EP1
3,c5JQp6xafqc,1677026,30555,712,0,6604,2021-10-10 15:50:03,공범 EP1
4,c5JQp6xafqc,1681824,30585,713,0,6600,2021-10-10 16:00:03,공범 EP1